### ISSUE TITLE
c-lightning hangs on estimatesmartfee

### ISSUE THREAD

**Issue by jb55** [gdassori/spruned#74]
I've been testing c-lightning with spruned on `v0.0.4b4`. It initially seemed to work ok and then I noticed c-lightning hangs when calling out to bitcoin-cli estimatesmartfee:

bitcoin-cli -rpcuser=rpcuser -rpcpassword=rpcpassword estimatesmartfee 2 CONSERVATIVE

logs:

```
Nov 17 23:18:14 monad spruned[2459]: 2018-11-17 23:18:14,312 - jsonrpcserver.dispatcher.request - INFO - {'method': 'echo', 'params': [], 'id': 1}
Nov 17 23:18:14 monad spruned[2459]: 2018-11-17 23:18:14,313 - aiohttp.access - INFO - 127.0.0.1 [18/Nov/2018:07:18:14 +0000] "POST / HTTP/1.1" 200 232 "-" "-"
Nov 17 23:18:14 monad spruned[2459]: 2018-11-17 23:18:14,317 - jsonrpcserver.dispatcher.request - INFO - {'method': 'estimatesmartfee', 'params': [2, 'CONSERVATIVE'], 'id': 1}
Nov 17 23:18:14 monad spruned[2459]: 2018-11-17 23:18:14,317 - spruned.dependencies.connectrum - DEBUG - Connecting to: <ServerInfo electrum-1.mempool.co nick=063a1a037135337b ports="['s']" v=1.2 prune=0>
Nov 17 23:18:14 monad spruned[2459]: 2018-11-17 23:18:14,322 - jsonrpcserver.dispatcher.request - INFO - {'method': 'getblockcount', 'params': [], 'id': 1}
Nov 17 23:18:14 monad spruned[2459]: 2018-11-17 23:18:14,325 - aiohttp.access - INFO - 127.0.0.1 [18/Nov/2018:07:18:14 +0000] "POST / HTTP/1.1" 200 236 "-" "-"
Nov 17 23:18:14 monad spruned[2459]: 2018-11-17 23:18:14,331 - jsonrpcserver.dispatcher.request - INFO - {'method': 'getblockhash', 'params': [550462], 'id': 1}
Nov 17 23:18:14 monad spruned[2459]: 2018-11-17 23:18:14,333 - aiohttp.access - INFO - 127.0.0.1 [18/Nov/2018:07:18:14 +0000] "POST / HTTP/1.1" 200 297 "-" "-"
Nov 17 23:18:14 monad spruned[2459]: 2018-11-17 23:18:14,342 - jsonrpcserver.dispatcher.request - INFO - {'method': 'getblock', 'params': ['00000000000000000003749e1a6fcb5ac92c3dc6a24a2c9890dd840b43f14313', False], 'id': 1}
Nov 17 23:18:14 monad spruned[2459]: 2018-11-17 23:18:14,347 - p2p - INFO - Block 550462 (00000000000000000003749e1a6fcb5ac92c3dc6a24a2c9890dd840b43f14313) provided in 0.0051s)
Nov 17 23:18:14 monad spruned[2459]: 2018-11-17 23:18:14,488 - aiohttp.access - INFO - 127.0.0.1 [18/Nov/2018:07:18:14 +0000] "POST / HTTP/1.1" 200 2277517 "-" "-"
Nov 17 23:18:14 monad spruned[2459]: 2018-11-17 23:18:14,985 - spruned.dependencies.connectrum - DEBUG - Transport connected ok
Nov 17 23:18:15 monad spruned[2459]: 2018-11-17 23:18:15,147 - spruned.dependencies.connectrum - DEBUG - Connected to: <ServerInfo electrum-1.mempool.co nick=063a1a037135337b ports="['s']" v=1.2 prune=0>
Nov 17 23:18:15 monad spruned[2459]: 2018-11-17 23:18:15,148 - p2p - INFO - Connected to peer electrum-1.mempool.co:s (ElectrumX 1.2.1)
Nov 17 23:18:15 monad spruned[2459]: 2018-11-17 23:18:15,148 - electrum - DEBUG - Peer raw response: ['ElectrumX 1.2.1', '1.2']
Nov 17 23:18:33 monad spruned[2459]: 2018-11-17 23:18:33,823 - pycoin - DEBUG - message <Peer ('23.98.43.170', 8333)>: addr (31 byte payload)
```

and then nothing else seems to be logged...

and when I stop clightning:

```
Nov 17 23:19:38 monad spruned[2459]: 2018-11-17 23:19:38,579 - aiohttp.server - ERROR - Unhandled exception
Nov 17 23:19:38 monad spruned[2459]: Traceback (most recent call last):
Nov 17 23:19:38 monad spruned[2459]:   File "/nix/store/rzhiz9s0gzmmpqh1xwzg2cj3mqv8ax8s-python3.6-aiohttp-3.3.2/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 398, in start
Nov 17 23:19:38 monad spruned[2459]:     await resp.prepare(request)
Nov 17 23:19:38 monad spruned[2459]:   File "/nix/store/rzhiz9s0gzmmpqh1xwzg2cj3mqv8ax8s-python3.6-aiohttp-3.3.2/lib/python3.6/site-packages/aiohttp/web_response.py", line 300, in prepare
Nov 17 23:19:38 monad spruned[2459]:     return await self._start(request)
Nov 17 23:19:38 monad spruned[2459]:   File "/nix/store/rzhiz9s0gzmmpqh1xwzg2cj3mqv8ax8s-python3.6-aiohttp-3.3.2/lib/python3.6/site-packages/aiohttp/web_response.py", line 605, in _start
Nov 17 23:19:38 monad spruned[2459]:     return await super()._start(request)
Nov 17 23:19:38 monad spruned[2459]:   File "/nix/store/rzhiz9s0gzmmpqh1xwzg2cj3mqv8ax8s-python3.6-aiohttp-3.3.2/lib/python3.6/site-packages/aiohttp/web_response.py", line 367, in _start
Nov 17 23:19:38 monad spruned[2459]:     await writer.write_headers(status_line, headers)
Nov 17 23:19:38 monad spruned[2459]:   File "/nix/store/rzhiz9s0gzmmpqh1xwzg2cj3mqv8ax8s-python3.6-aiohttp-3.3.2/lib/python3.6/site-packages/aiohttp/http_writer.py", line 100, in write_headers
Nov 17 23:19:38 monad spruned[2459]:     self._write(buf)
Nov 17 23:19:38 monad spruned[2459]:   File "/nix/store/rzhiz9s0gzmmpqh1xwzg2cj3mqv8ax8s-python3.6-aiohttp-3.3.2/lib/python3.6/site-packages/aiohttp/http_writer.py", line 57, in _write
Nov 17 23:19:38 monad spruned[2459]:     raise ConnectionResetError('Cannot write to closing transport')
Nov 17 23:19:38 monad spruned[2459]: ConnectionResetError: Cannot write to closing transport
```

perhaps there's some hanging callback somewhere?

**Comment by jb55** [comment]
Not sure if related:

```
Nov 17 23:24:03 monad spruned[2459]: 2018-11-17 23:24:03,666 - asyncio - ERROR - Task was destroyed but it is pending!
Nov 17 23:24:03 monad spruned[2459]: task: <Task pending coro=<_make_repeated_f.<locals>.repeated_f() running at /nix/store/fziji8g9jmxq1gjfknnw51scxizfdp1d-spruned-0.0.4b4/lib/python3.6/site-packages/spruned/dependencies/pycoinnet/MappingQueue.py:55> wait_for=<Future cancelled> cb=[gather.<locals>._done_callback(0)() at /nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/asyncio/tasks.py:622]>
Nov 17 23:24:03 monad spruned[2459]: 2018-11-17 23:24:03,666 - asyncio - ERROR - Task was destroyed but it is pending!
Nov 17 23:24:03 monad spruned[2459]: task: <Task pending coro=<_make_repeated_f.<locals>.repeated_f() running at /nix/store/fziji8g9jmxq1gjfknnw51scxizfdp1d-spruned-0.0.4b4/lib/python3.6/site-packages/spruned/dependencies/pycoinnet/MappingQueue.py:58> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fbc55ddecd8>()]> cb=[gather.<locals>._done_callback(0)() at /nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/asyncio/tasks.py:622]>
Nov 17 23:24:03 monad spruned[2459]: 2018-11-17 23:24:03,666 - asyncio - ERROR - Task was destroyed but it is pending!
Nov 17 23:24:03 monad spruned[2459]: task: <Task pending coro=<Queue.get() running at /nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/asyncio/queues.py:167> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fbc55dde828>()]> cb=[_wait.<locals>._on_completion() at /nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/asyncio/tasks.py:380]>
Nov 17 23:24:09 monad spruned[2459]: 2018-11-17 23:24:09,086 - pycoin - DEBUG - message <Peer ('23.98.43.170', 8333)>: addr (31 byte payload)
Nov 17 23:24:12 monad spruned[2459]: 2018-11-17 23:24:12,816 - asyncio - ERROR - Task was destroyed but it is pending!
Nov 17 23:24:12 monad spruned[2459]: task: <Task pending coro=<_make_repeated_f.<locals>.repeated_f() running at /nix/store/fziji8g9jmxq1gjfknnw51scxizfdp1d-spruned-0.0.4b4/lib/python3.6/site-packages/spruned/dependencies/pycoinnet/MappingQueue.py:55> wait_for=<Future cancelled> cb=[gather.<locals>._done_callback(0)() at /nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/asyncio/tasks.py:622]>
Nov 17 23:24:12 monad spruned[2459]: 2018-11-17 23:24:12,816 - asyncio - ERROR - Task was destroyed but it is pending!
Nov 17 23:24:12 monad spruned[2459]: task: <Task pending coro=<Queue.get() running at /nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/asyncio/queues.py:167> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fbc30451df8>()]> cb=[_wait.<locals>._on_completion() at /nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/asyncio/tasks.py:380]>
Nov 17 23:24:12 monad spruned[2459]: 2018-11-17 23:24:12,816 - asyncio - ERROR - Task was destroyed but it is pending!
Nov 17 23:24:12 monad spruned[2459]: task: <Task pending coro=<_make_repeated_f.<locals>.repeated_f() running at /nix/store/fziji8g9jmxq1gjfknnw51scxizfdp1d-spruned-0.0.4b4/lib/python3.6/site-packages/spruned/dependencies/pycoinnet/MappingQueue.py:58> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fbaf9286858>()]> cb=[gather.<locals>._done_callback(0)() at /nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/asyncio/tasks.py:622]>
Nov 17 23:24:12 monad spruned[2459]: 2018-11-17 23:24:12,816 - asyncio - ERROR - Task was destroyed but it is pending!
Nov 17 23:24:12 monad spruned[2459]: task: <Task pending coro=<_make_repeated_f.<locals>.repeated_f() running at /nix/store/fziji8g9jmxq1gjfknnw51scxizfdp1d-spruned-0.0.4b4/lib/python3.6/site-packages/spruned/dependencies/pycoinnet/MappingQueue.py:55> wait_for=<Future cancelled> cb=[gather.<locals>._done_callback(0)() at /nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/asyncio/tasks.py:622]>
Nov 17 23:24:12 monad spruned[2459]: 2018-11-17 23:24:12,816 - asyncio - ERROR - Task was destroyed but it is pending!
Nov 17 23:24:12 monad spruned[2459]: task: <Task pending coro=<_make_repeated_f.<locals>.repeated_f() running at /nix/store/fziji8g9jmxq1gjfknnw51scxizfdp1d-spruned-0.0.4b4/lib/python3.6/site-packages/spruned/dependencies/pycoinnet/MappingQueue.py:58> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fbc54202a98>()]> cb=[gather.<locals>._done_callback(0)() at /nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/asyncio/tasks.py:622]>
Nov 17 23:24:12 monad spruned[2459]: 2018-11-17 23:24:12,817 - asyncio - ERROR - Task was destroyed but it is pending!
Nov 17 23:24:12 monad spruned[2459]: task: <Task pending coro=<Queue.get() running at /nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/asyncio/queues.py:167> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fbc542020a8>()]> cb=[_wait.<locals>._on_completion() at /nix/store/nrl0l79a48924xb0897ap572xf29ciir-python3-3.6.6/lib/python3.6/asyncio/tasks.py:380]>

```

**Comment by gdassori** [comment]
Looks like this was related to the blocks hitrate, and not estimatefee.
I still have some issues with estimatefee, but it's not related to this bug.

The asyncio errors are handled logged errors. I guess this log was in debug mode.
