### ISSUE TITLE
Got "TypeError: must be str, not list" when run spruned first time

### ISSUE THREAD

**Issue by hikaman** [gdassori/spruned#75]
Tried to run on RPI Zero W with Raspbian GNU/Linux 9.6 (stretch)
and 
Python 3.6.5

followed the instructions until
>$ ~/src/spruned/venv/bin/spruned

got stuck with following issue

(venv) pi@raspberrypi:~/src/spruned $ ~/src/spruned/venv/bin/spruned
Traceback (most recent call last):
  File "/home/pi/src/spruned/venv/bin/spruned", line 11, in <module>
    load_entry_point('spruned==0.0.4b4', 'console_scripts', 'spruned')()
  File "/home/pi/src/spruned/venv/lib/python3.6/site-packages/spruned-0.0.4b4-py3.6.egg/spruned/app.py", line 92, in main
    from spruned.main import main_task
  File "/home/pi/src/spruned/venv/lib/python3.6/site-packages/spruned-0.0.4b4-py3.6.egg/spruned/main.py", line 4, in <module>
    from spruned.builder import cache, headers_reactor, blocks_reactor, jsonrpc_server, repository
  File "/home/pi/src/spruned/venv/lib/python3.6/site-packages/spruned-0.0.4b4-py3.6.egg/spruned/builder.py", line 43, in <module>
    jsonrpc_server, headers_reactor, blocks_reactor, repository, cache = builder(_ctx)
  File "/home/pi/src/spruned/venv/lib/python3.6/site-packages/spruned-0.0.4b4-py3.6.egg/spruned/builder.py", line 14, in builder
    electrod_connectionpool, electrod_interface = electrod_builder(ctx)
  File "/home/pi/src/spruned/venv/lib/python3.6/site-packages/spruned-0.0.4b4-py3.6.egg/spruned/daemon/electrod/__init__.py", line 43, in build
    _ = [fees_collector.add_peer(peer) for peer in [x[0] + '/' + x[1] for x in peers]]
  File "/home/pi/src/spruned/venv/lib/python3.6/site-packages/spruned-0.0.4b4-py3.6.egg/spruned/daemon/electrod/__init__.py", line 43, in <listcomp>
    _ = [fees_collector.add_peer(peer) for peer in [x[0] + '/' + x[1] for x in peers]]
TypeError: must be str, not list

Any tipps or hints are very welcome!

**Comment by gdassori** [comment]
Hi, looks like an unhandled corner, I'll look into it. 
Thanks!

**Comment by gdassori** [comment]
Could you please try to reproduce it on 0.0.5.1 ?
Thanks.

**Comment by gdassori** [comment]
Please reopen if needed
