### ISSUE TITLE
Got "Namespace object has no attribute" when run spruned first time

### ISSUE THREAD

**Issue by dmar198** [gdassori/spruned#77]
Installed spruned on Raspberry Pi 3 Model B. OS is Raspbian Stretch Lite and python version is Python 3.5.3. Got to this part:

> $ ~/src/spruned/venv/bin/spruned

Then I got this:

$ ~/src/spruned/venv/bin/spruned
Traceback (most recent call last):
  File "/home/admin/src/spruned/venv/bin/spruned", line 11, in <module>
    load_entry_point('spruned==0.0.4b4', 'console_scripts', 'spruned')()
  File "/home/admin/src/spruned/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/admin/src/spruned/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/home/admin/src/spruned/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/admin/src/spruned/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/admin/src/spruned/venv/lib/python3.5/site-packages/spruned-0.0.4b4-py3.5.egg/spruned/app.py", line 122, in <module>
    ctx.load_args(args)
  File "/home/admin/src/spruned/venv/lib/python3.5/site-packages/spruned-0.0.4b4-py3.5.egg/spruned/application/context.py", line 151, in load_args
    'cache_size': int(args.cache_size),
AttributeError: 'Namespace' object has no attribute 'cache_size'

**Comment by fluidvoice** [comment]
Try running it from within the Spruned directory:
~/src/spruned/venv/bin $ `./spruned --debug`

**Comment by afilini** [comment]
Had the same issue, see #78, it should fix that problem

**Comment by gdassori** [comment]
Thnks @afilini, fix merged. 
Will release on pypy this w.e. along with other fixes.
