### ISSUE TITLE
c-lightning crash caused by spruned reply on getblock

### ISSUE THREAD

**Issue by dakk** [gdassori/spruned#85]
```
+3174.769073984 lightningd(12722):UNUSUAL: bitcoin-cli: finished bitcoin-cli -testnet -rpcport=8339 -rpcuser=... -rpcpassword=... getblock 0000000000004d37aec7ddcff646f7e2f84424f77379b664f76b017684cc6f1b false (16970 ms)
+3174.769479243 lightningd(12722):BROKEN: bitcoin-cli -testnet -rpcport=8339 -rpcuser=... -rpcpassword=... getblock 0000000000004d37aec7ddcff646f7e2f84424f77379b664f76b017684cc6f1b false exited 1 (after 4 other errors) 'error code: -1?error message:?Server error?'
+3174.803950086 lightningd(12722):BROKEN: FATAL SIGNAL 6 (version v0.7.0-262-g0fc4241)
```

**Comment by gdassori** [comment]
Please try the latest version (0.0.8).
Seems a corner case, the new release has some changes on that side.

**Comment by dakk** [comment]
Now I got a different problems:

# Start failure

On cleaned .spruned, spruned hangs on this error:
```
2019-04-26 07:55:23,140 - root - DEBUG - Database migrations. Current version: 0, migrations available: 2
2019-04-26 07:55:23,157 - root - DEBUG - Arguments: Namespace(add_p2p_peer=None, cache_size=50, daemon=False, datadir='/root/.spruned', debug=True, disable_electrum_peer_discovery=False, disable_p2p_peer_discovery=False, electrum_server=None, keep_blocks=200, max_electrum_connections=None, max_p2p_connections=None, mempool_size=0, network='bitcoin.testnet', no_dns_seed=False, proxy=None, rpcbind='127.0.0.1', rpcpassword='test', rpcport='8339', rpcuser='test', tor=False, zmqpubhashblock='', zmqpubhashtx='', zmqpubrawblock='', zmqpubrawtx='')
2019-04-26 07:55:23,159 - leveldb - DEBUG - Ensuring integrity of the storage, and tracking missing items
2019-04-26 07:55:23,159 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished coro=<main_task() done, defined at ./spruned/main.py:10> exception=RuntimeError('Database is closed',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "./spruned/main.py", line 16, in main_task
    await loop_check_integrity(loop)
  File "./spruned/main.py", line 38, in loop_check_integrity
    await repository.ensure_integrity()
  File "./spruned/repositories/repository.py", line 66, in ensure_integrity
    self._ensure_no_stales_in_blockchain_repository()
  File "./spruned/application/database.py", line 91, in decorator
    _local.storage_ldb = storage_ldb.write_batch()
  File "plyvel/_plyvel.pyx", line 348, in plyvel._plyvel.DB.write_batch
RuntimeError: Database is closed
```

I can continue using ctrl+c, but c-lightning crashes at some blocks:

```
+9.693508700 lightningd(7085):BROKEN: bitcoin-cli -testnet -rpcport=8339 -rpcuser=... -rpcpassword=... getblock 00000000000000602c06d2cbb4cda5d2887974
59618f024ca88bd7afa6ef5945 false: bad block '00000020a74ca86f50e6b707680bf4e4737f70e9e08414f1c33742f459000000000000003a457a4b2f22a6f0a0e38a8beee5217f7
d77a1b45d3533bc1cb27cb41cbef0f78039c15c28f7031a6c5234e3010000000001010000000000000000000000000000000000000000000000000000000000000000ffffffff2b03cd121
700048039c15c0402cb5f1c0caff98f5c42c80000000000000a636b706f6f6c072f74727466782fffffffff0273f856020000000017a9146b5233d5b41019fbf5132690b85731e043176de
9870000000000000000266a24aa21a9ed29c6910191f77c186f6310759c54085ef3572105d0938c48d11ce9d9722a2d6e01200000000000000000000000000000000000000000000000000
000000000000000000000000100000001688a185a06478fd9580629c577672d6a9635851e808094d0aeffa96f18935198020000006a4730440220111a17162c5b733ad21649815b4268563
a299575eee4b8b6eac395e549ebefe202201792e6f521bb59410ce1a05822c1a29e589a3993e33ec86e088b7aad11ff8ba20121039675c2d16f697f2f2f87b11aef636912ffc75f9f57d81
e3f1b3a529652ecb247ffffffff03ca8b4500000000001976a914f90bba6b3f76606f08832a4ad311174329f050c488ac40420f00000000001976a914f310513bfc8ef680a8889091136d3
1c3ffd8880488ace8030000000000001976a914973674c24f12f79fa05d14d3412405f217380f7088ac0000000002000000000101fc43895d64fd74e629b3e5cd9d4ce9e778df02374c1dc
47e5d853dc5482d10ed0100000017160014b6b8fc7855487b80acd1ad156c0231db95725166feffffff02ddba5900000000001976a9145a101d0ddf97461c93bdc740708e8d0c2613181d8
8ac85e2afcd0000000017a9142563e38f0b628a79ad59bb283a65c082bf9f9cd7870247304402201945e1c9c7d5cf543aac261b7cb2ffe68d8b2ea6477a1490e0a6f4f8cc9cc8820220290
6c02dd54dae87e3c9d6bf5f2f7342eb99ad6a685975c55548d9230376246f01210338567a0df918605290730e5604bd1013cbab7a5cfe43641b0551702069fc2fcacc12170002000000000
1016723031241787596eef91ec6067b14309f0ba96c769d61cc908c96b221bd6570000000001716001443ef08a8bca4432e16c6e58c93e99a9feee5632ffeffffff02434afd00000000001
60014e321f88c3b627c88a2c425a4c103e5ff62b45e2514c0c8740100000016001441a07f95cab878db3390d07291f433b42168b70202473044022031c6c66e885511830e21b17310cf2d2
7c386e01358a765fc8ffbb286e9ffc82802200a26c82500de9f0b2d0dd2dd2209b073a99d0d64014bbc685ad5d0dbd25a628b0121025ef5a6bbf68ffd2c2b0375a78da1271511d81169b87
b2d008a6a02d04cef2f7ccc121700010000000001010f40c7d180c34daedf94c113c52f88f9c1329c89ee4cc3d6cbdc684b1ed6b73e0100000000f0ffffff0340420f0000000000160014d
b7d6eefa1b10568f9acbfb2ac772b37357af0941223300000000000160014c548abf4a380a8dcd9288dd7af19524e3c0fc3eb0000000000000000196a1768747470733a2f2f746274632e6
269746170732e636f6d02483045022100ba75b8567971fc44391b2422d419bf446eb467098bb50345544f36c58744cc430220719a2145b59b2ac84746ea0e4b78c611d551f56516a41a3aa
4f3e5db66cf8e0f0121022622abf3d0ab895f8a951b88be0b16b342c7c96ad7fd9d869dcc7a82e44f631c0000000001000000000101504785e18e244b8a99c0516b5ccebec8b63174ac774
75258b55f1536e57828400100000000f0ffffff0340420f0000000000160014525ab8d407189304ce7ced0ecee0bf662d73473588cf260000000000160014d1c41fba3aaa55cd64eea3428
51438ccce3d7ae80000000000000000196a1768747470733a2f2f746274632e6269746170732e636f6d02483045022100cc3a3d668d275cf0ce458b3436f3eaa427af2893cf07e303a28d5
2aad8cea0830220700fe50e64b08b3b5cfc380bc07edae26ef5f9708fa1ba64f078c7b78c7618a7012102609ae03fe43a735850b8a6dd0fb14d9295db80eb39c8cb819642caef27f5f5f30
000000001000000000101baf5a3377daf2684c488a9a0cf3c72a067008a6e4d2b33339291930deaa328ff0100000000f0ffffff0340420f0000000000160014512a0f38e47bc534d32574f
a475f782b41cca1cee3b22600000000001600148ebceaa6172a7f0e9557c2dba783fbf7956112ff0000000000000000196a1768747470733a2f2f746274632e6269746170732e636f6d024
83045022100c73f07d048ca0d94cd0ec1b0e43ee85dbbfe75266fd38f0f41af019ba9a837e1022000b2bcc7949cfc0ad4bce86b341ae291ea230a900aee16d94b79a678d46f7f9a0121028
2ca0dce2e2bba0efe071e01a4aed9fcd5ed0f11a0ce12ad0776e103b61830f40000000001000000000101a3cc14e2b6b6149d4b44e074388a1a0507b644aed00d9353e29bb3e9cc4cdec70
100000000f0ffffff0340420f000000000017a914c69534b4b9ed34d3a7a398032e3b11c7f5706061877c46320000000000160014028c233fcf503588c76acc8cc643397d0f467c7e00000
00000000000196a1768747470733a2f2f746274632e6269746170732e636f6d02483045022100c32a3fdaf4672a63dae116edfb1a49736ebb2245c2854afef131d6f57b429f0202205816b
c3c7df02f3f7ae74e889a98350859ae3806124efedaee6fb72652a6bc31012102385ba19b55398a3a80cd41b70b7d67f1083d3ec4ed2861d2e5df137f99a2ee16000000000100000000010
1d9740c7314cb03671d0e42f90bbcda09f9ee0ef02e1ca47301f1ab125239050e0100000000f0ffffff0340420f00000000001976a914138bf16cf4cbaaddfc62810f3e0ad69ef33e2e6a8
8acaa9e2e00000000001600145d48e6bf5982fbc6c0662be1d6963e3b23c6e0900000000000000000196a1768...
```

After a spruned cleanup and resync, I got the same problem but in different blocks, for example:

```
+305.120823453 lightningd(7263):DEBUG: Adding block 1512204: 00000000d2bbee936d24c4c74a1b2c6113ba3a17c7ef0b4fddab2317a4d7373b
+320.606851163 lightningd(7263):UNUSUAL: bitcoin-cli: finished bitcoin-cli -testnet -rpcport=8339 -rpcuser=... -rpcpassword=... getblock 00000000f8da4
f5253e4a108fe4d7a967f8b7b320e4d4cfe6dd53d0c025fee5f false (15326 ms)
+320.609906541 lightningd(7263):DEBUG: Adding block 1512205: 00000000f8da4f5253e4a108fe4d7a967f8b7b320e4d4cfe6dd53d0c025fee5f
+321.026931910 lightningd(7263):BROKEN: bitcoin-cli -testnet -rpcport=8339 -rpcuser=... -rpcpassword=... getblock 00000000000003f19de64ef903c4d14320dd
85d36bccbfe9d2c2ca1e061c01f8 false: bad block '000000205fee5f020c3dd56dfe4c4d0e327b8b7f967a4dfe08
```

This is blocking cause even restarting c-lightning, the problem won't solve

**Comment by gdassori** [comment]
The blocking bug you reported urged a new release and should be fixed in the latest (0.0.9).

**Comment by dakk** [comment]
I'm trying it, but now after header sync doesn't connect to peers:

```
2019-04-29 07:14:55,527 - electrum - INFO - Last processed header: 1513202 (000000000000030f71b2c88f1f68af174b9af7485af441e60fcdb929d413444c)
2019-04-29 07:14:55,527 - electrum - DEBUG - -1 headers behind, downloading
2019-04-29 07:14:55,532 - p2p - INFO - Bootstrap: ConnectionPool not ready yet
2019-04-29 07:14:58,783 - p2p - WARNING - Peers not loaded yet
2019-04-29 07:15:03,707 - electrum - DEBUG - Fallback headers check: No best header or too recent header (107), trying again in 553
2019-04-29 07:15:03,784 - p2p - WARNING - Peers not loaded yet
2019-04-29 07:15:08,788 - p2p - WARNING - Peers not loaded yet
2019-04-29 07:15:13,793 - p2p - WARNING - Peers not loaded yet
2019-04-29 07:15:18,798 - p2p - WARNING - Peers not loaded yet
2019-04-29 07:15:23,804 - p2p - WARNING - Peers not loaded yet
2019-04-29 07:15:25,533 - p2p - INFO - Bootstrap: ConnectionPool not ready yet
2019-04-29 07:15:28,807 - p2p - WARNING - Peers not loaded yet
2019-04-29 07:15:33,811 - p2p - WARNING - Peers not loaded yet
2019-04-29 07:15:38,814 - p2p - WARNING - Peers not loaded yet
2019-04-29 07:15:43,818 - p2p - WARNING - Peers not loaded yet
2019-04-29 07:15:48,823 - p2p - WARNING - Peers not loaded yet
2019-04-29 07:15:53,828 - p2p - WARNING - Peers not loaded yet
2019-04-29 07:15:55,535 - p2p - INFO - Bootstrap: ConnectionPool not ready yet
2019-04-29 07:15:58,832 - p2p - WARNING - Peers not loaded yet
2019-04-29 07:16:03,834 - p2p - WARNING - Peers not loaded yet
2019-04-29 07:16:08,840 - p2p - WARNING - Peers not loaded yet
2019-04-29 07:16:13,843 - p2p - WARNING - Peers not loaded yet
```

**Comment by gdassori** [comment]
Almost everything fixed, still having problems on RuntimeError: Database is closed.
Problem deserve a dedicated issue.

**Comment by supertestnet** [comment]
I am having a similar problem at blockheight 608232. I used curl to test the getblock command. The command "getblock [hash representing block 608231]" works just fine, as does the command getblock [hash representing block 608233], but when I do getblock [hash representing block 608232], the command either just hangs, or I get this message: {"id": "curltest", "result": null, "error": {"code": -1, "message": "Server error"}, "jsonrpc": "2.0"}
